language: objective-c
osx_image: xcode8
sudo: false
rvm: 2.3.1
install: bundle install --without=documentation --path ../travis_bundle_dir
script: xcodebuild -scheme SlidableImage -project SlidableImage.xcodeproj -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone SE,latest' -configuration Debug ONLY_ACTIVE_ARCH=NO build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES="" CODE_S_IDENTITY="" CODE_SIGNING_REQUIRED=NO
after_success: slather
