language: objective-c
osx_image: xcode9
sudo: false
cache: cocoapods
before_install:
- gem install cocoapods
- pod repo update --silent
- pod install
script: xcodebuild -scheme SlidableImage -workspace SlidableImage.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.0' build test
after_success: bash <(curl -s https://codecov.io/bash) -J 'SlidableImage'
