language: objective-c
osx_image: xcode8
sudo: false
before_install:
  - open -b com.apple.iphonesimulator
  - gem install slather --no-document
  - gem install fastlane --no-document
script: fastlane testing
